export const OBTENER_VIDEOJUEGOS = "OBTENER_VIDEOJUEGOS";
export const ORDENAR_POR_NOMBRE = "ORDENAR_POR_NOMBRE";
export const ORDENAR_POR_RATING = "ORDENAR_POR_RATING";
export const SET_TOTAL_PAGINAS = "SET_TOTAL_PAGINAS";
export const SET_PAGINA_ACTUAL = "SET_PAGINA_ACTUAL";
export const OBTENER_VIDEOJUEGOS_DB = "OBTENER_VIDEOJUEGOS_DB";
export const OBTENER_GENEROS = "OBTENER_GENEROS";
